### PR TITLE
Return total file length in blobnet header

### PR DESCRIPTION
**Pull request by aksh-at**
Planning on storing mount sizes in the server. Returning file length in the `GET` response header, so we can add up the final mount size in the server `MountBuild` method.

image

### CODE REVIEW

**Comment by erikbern** [comment]
why couldn't the client just use the number of bytes in the payload?

**Comment by aksh-at** [comment]
> why couldn't the client just use the number of bytes in the payload?

This is primarily for file existence check requests. Those have X-Bn-Range="0-0" in the header, which means that no content is returned—just a 404 if file isn't found.

During `MountBuild` we check the presence for all files, and don't have access to (or need) the entire file contents.

**Comment by erikbern** [comment]
ok, cool. I guess a REST puritan would use HEAD for that, but it's not important

**Review by ekzhang — APPROVED** [review]
If CI passes feel free to merge! Release process is the same as cadre: "cargo release" command with version update

**Pull request merged**
