### PR TITLE
perf: Remove CPU-expensive unused sha256 calc

### PR DESCRIPTION
**Pull request by thundergolfer**
I'm looking into MOD-1116 and the flamegraph of the benchmark I added, `snapshot.rs`, shows a lot of time being spent shasum-ing the file three times:

1. Client-side, processing file for image index
2. Client-side, in `.put` of remote provider
3. On server-side in `.put` of local dir provider

The second isn't used, so I'm removing it here.

The `snapshot.rs` benchmark shows a 12-15% improvement from doing this

<kbd>
image
</kbd>

**Rust sha256 hashing perf**

Adding my notes from looking into this, for posterity. The TLDR is that there's no trivial way to boost perf of sha256 hashing:

---

- OpenSSL is fast, 1GiB/s, on my devbox:

```
(venv) ubuntu@ip-123-45-67-89:~/modal$ time openssl dgst -sha256 1GB.bin
SHA256(1GB.bin)= ffde13aa16745f40d34427ea68fa3c0a81158b767f2524db53b382b3c8cc3f34
real 0m1.006s
user 0m0.838s
sys 0m0.168s
```

- We could use OpenSSL's impl by dynamic linking against it in the worker. 
- The `sha2` Rust implementation is a respectable ~400MiB/s
- [https://users.rust-lang.org/t/hash-digest-performance-rust-vs-python/89686/21](https://users.rust-lang.org/t/hash-digest-performance-rust-vs-python/89686/21)
    - if I do the test above on my devbox, the `asm` feature is no faster than default impl which uses std instrinsics
    - Adding `asm` and running the `snapshot.rs` benchmark also showed no performance difference.

### Refs

- MOD-1116
- MOD-1019

### CODE REVIEW

**Comment by erikbern** [comment]
Is the main bottleneck just pushing data to EFS?

**Comment by thundergolfer** [comment]
> Is the main bottleneck just pushing data to EFS?

I don't think so, thankfully. I can reproduce the slowness locally.

**Review by ekzhang — APPROVED** [review]
Yes, this looks good to me, great find! I didn't realize SHA-256 added so much CPU overhead.

If it's bottlenecked on SHA-256 in the end-to-end flamegraph on prod, there are other things we can remove at the cost of some API complexity :)

**Review by ekzhang — APPROVED** [review]
Yes, this looks good to me, great find! I didn't realize SHA-256 added so much CPU overhead.

If it's bottlenecked on SHA-256 in the end-to-end flamegraph on prod, there are other things we can remove at the cost of some API complexity :)

**Comment by danielnorberg** [comment]
Big change but maybe we could consider a tree hash? That would be parallelizable.

**Pull request merged**
