### PR TITLE
clippy lint

### PR DESCRIPTION
**Pull request by thundergolfer**
I can't get `clippy` to complain locally, but its failing in CI https://github.com/modal-labs/blobnet/actions/runs/4394817340/jobs/7696102333

The lint makes sense. Don't what `clippy` config/version problem is stopping this showing up on my devbox.

### CODE REVIEW

**Comment by ekzhang** [comment]
You might need to `rustup update stable` since we don't pin the Rust version used for CI here

**Comment by thundergolfer** [comment]
I did that. But... 

```
cargo clippy --version
clippy 0.1.66 (90743e7 2023-01-10)
```

might not have worked...

**Comment by ekzhang** [comment]
Ah yes, after updating it should say `clippy 0.1.68 (2c8cc343 2023-03-06)`. :)

**Comment by thundergolfer** [comment]
Yeh once pulling `main` in modal repo the `rust-toolchain` file set the version correctly. I also ran `rustup default 0.1.68` and now the blobnet repo shows 0.1.68 for clippy 🤷

**Pull request merged**
