### PR TITLE
Call fdatasync(2) after large file writes to disk

### PR DESCRIPTION
**Pull request by ekzhang**
As found by @thundergolfer after a lot of benchmarking. All credit to him.

I wonder if we should just merge this and see what the outcome is, or if there's some more testing we could do. I'm not sure what exact metric we would want to measure in those tests / what specific questions are left over about file system behavior, so I'm leaning towards just merging it.

### Benchmarks

Flushing the page cache to disk indeed seems to be doing nontrivial work. See the `image_delayed/cold` benchmark. :)

image

### CODE REVIEW

**Comment by erikbern** [comment]
Nice – I think it makes sense to merge this!

**Comment by thundergolfer** [comment]
I think we should merge this too, but before that I'd like to look at this failure I got running the benchmarks:

image

**Comment by thundergolfer** [comment]
@ekzhang I've cherry-pick a commit onto this branch and pushed. It moves the sync operation to after the `link`, and in local benchmark executions doesn't present the `file not found` errors while also alleviating the buffer cache backup experienced in the large_image_data benchmark. It's the same file descriptor getting sync'd, so the data should be getting flushed just the same.

**Comment by ekzhang** [comment]
Wow, great find with the fsync issues with directory creation. That's so interesting.

**Comment by erikbern** [comment]
Wait, are we copying the whole file? Won't that cause the 4GB file to be written _twice_ to disk?

**Comment by ekzhang** [comment]
Sorry could you provide a couple more details on what you mean?

In production right now, if you write a 4 GB file into blobnet, it will be added to EFS. Then on the `blobnet.worker.internal` node it will be saved in 2 MB chunks into a folder on disk. And when requested from the client, it will be saved into cache lazily in 2 MB chunks into a folder on disk as well.

**Comment by erikbern** [comment]
I see what you're saying. Makes sense!

**Review by thundergolfer — APPROVED** [review]

**Pull request merged**
