### PR TITLE
[MOD-1281] sync data before linking file into cache dir

### PR DESCRIPTION
**Pull request by danielnorberg**
Ensure that file contents are synced before linking it into place in origin or cache dir.

See https://github.com/influxdata/influxdb_iox/pull/6399#discussion_r1048443657

Fixes MOD-1281

Also see https://github.com/modal-labs/blobnet/pull/18

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by danielnorberg** [comment]
Stress tested together with https://github.com/modal-labs/blobnet/pull/65 with up thousands of connections without visible issues.

**Review by thundergolfer — COMMENTED** [review]
This seems to be re-introing https://github.com/modal-labs/blobnet/pull/18/commits/1cb23e90d62949392234cd1ef8da8b6fb13d8eec

But do we have an idea of why or why not this would produce the `file not found` issues?

**Comment by danielnorberg** [comment]
> This seems to be re-introing [1cb23e9](https://github.com/modal-labs/blobnet/commit/1cb23e90d62949392234cd1ef8da8b6fb13d8eec)
> 
> But do we have an idea of why or why not this would produce the `file not found` issues?

It does not seem to me that this should produce `file not found` errors and I wasn’t able to observe any in the added test nor manual stress testing. Where were these errors observed and how can they be reproduced?

**Comment by thundergolfer** [comment]
They came up when running the Cargo benchmarks. Described in https://github.com/modal-labs/blobnet/pull/18

Unfortunately I couldn't come up with a theory of why it was happening, and I spent a lot of time looking at it.

**Comment by danielnorberg** [comment]
Ok, I’ll try to reproduce and see what’s going on.

**Review by thundergolfer — APPROVED** [review]
If you can't reproduce I think let's go with this. Could be a rabbit hole.

**Comment by danielnorberg** [comment]
@thundergolfer I believe the file not found errors were due to the benchmark deleting the temp cache dir while cache writes were ongoing. See https://github.com/modal-labs/blobnet/pull/72.

Merging that PR into this and running the benchmark I do not see any such errors:

```
     Running benches/read_benchmark.rs (target/release/deps/read_benchmark-fd867b7d0ede9776)
Gnuplot not found, using plotters backend
image_delayed/cold      time:   [1.5779 s 1.5825 s 1.5872 s]
                        change: [-2.2637% -1.3478% -0.3575%] (p = 0.02 < 0.05)
                        Change within noise threshold.
image_delayed/warm      time:   [298.58 ms 300.12 ms 301.94 ms]
                        change: [-0.1802% +0.4759% +1.1008%] (p = 0.21 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
```

**Pull request merged**
